name = "CloudBenchmarks"
uuid = "128a3188-ac61-41e7-9373-75758cb91c5b"
version = "0.1.0"
authors = ["quinnj <quinn.jacobd@gmail.com>"]

[deps]
CloudBase = "85eb1798-d7c4-4918-bb13-c944d38e27ed"
CloudStore = "3365d9ee-d53b-4a56-812d-5344d5b716d7"
ConcurrentUtilities = "f0e56b4a-5159-44fe-b623-3e5288b988bb"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
Mmap = "a63ad114-7e13-5084-954f-fe012c677804"
PProf = "e4faabce-9ead-11e9-39d9-4379958e3056"
Profile = "9abbd945-dff8-562f-b5e8-e1ebf5ef1b79"
Reseau = "802f3686-a58f-41ce-bb0c-3c43c75bba36"

[sources]
CloudStore = {url = "https://github.com/JuliaServices/CloudStore.jl.git", rev = "compat/http-2"}
HTTP = {url = "https://github.com/JuliaWeb/HTTP.jl.git", rev = "perf/high-concurrency-client-throughput"}
Reseau = {url = "https://github.com/JuliaServices/Reseau.jl.git", rev = "perf/avoid-redundant-deadline-scheduling"}

[compat]
CloudBase = "=1.6.0"
CloudStore = "=1.7.0"
HTTP = "=2.6.2"
PProf = "3"
Reseau = "=1.3.5"
julia = "1.12, 1.13"
