name = "CloudBenchVM"
uuid = "86ef4d2b-47b1-460e-8b4f-783fac126226"
version = "0.1.0"
authors = ["quinnj <quinn.jacobd@gmail.com>"]

[deps]
CloudBase = "85eb1798-d7c4-4918-bb13-c944d38e27ed"
CloudBenchmarks = "128a3188-ac61-41e7-9373-75758cb91c5b"
CloudStore = "3365d9ee-d53b-4a56-812d-5344d5b716d7"
Reseau = "802f3686-a58f-41ce-bb0c-3c43c75bba36"

[sources]
CloudBase = {url = "https://github.com/JuliaServices/CloudBase.jl.git", rev = "jq-reseau-http"}
CloudBenchmarks = {path = ".."}
CloudStore = {url = "https://github.com/JuliaServices/CloudStore.jl.git", rev = "jq-reseau-http"}
Reseau = {url = "https://github.com/JuliaServices/Reseau.jl.git", rev = "main"}
